name: Cache Demo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache
          key: cache-c1aabfc

      - name: prime-cache-c1aabfc
        run: echo "Cache hit? ${{ steps.cache-deps.outputs.cache-hit }}"
